### ISSUE TITLE
Try to add this to Pi-apps

### ISSUE THREAD

**Issue by G265Dev** [piware14/pi-ware#67]
What does this suggestion do to pi-ware?

This will grow the number of users that pi-ware has :)

Why should we add this?

More apps would be built to be to be in the pi-ware store for Raspberry Pi and it would benefit you guys with the more help of some of the contributors from pi-apps.

**Comment by gl91306** [comment]
The reason were not adding our app store to pi-apps is because we are a separate app store, rather than an app. The pi-ware project is also not maintained, as you can see with the last commit being 2 years ago. We initially wanted this to be a "competitor/alternative" to pi-apps, but pi-apps is basically the default raspberry pi app store at this point so it doesn't matter. Besides, we only have 10 or so apps, and most of them are on pi-apps anyways, and the rest could easily added to pi-apps without any issue.

**Comment by G265Dev** [comment]
> The reason were not adding our app store to pi-apps is because we are a separate app store, rather than an app. The pi-ware project is also not maintained, as you can see with the last commit being 2 years ago. We initially wanted this to be a "competitor/alternative" to pi-apps, but pi-apps is basically the default raspberry pi app store at this point so it doesn't matter. Besides, we only have 10 or so apps, and most of them are on pi-apps anyways, and the rest could easily added to pi-apps without any issue.

Fair enough.

Also a suggestion in the readme on pi-ware include a way of installing python3, tk, ttkthemes and screeninfo
Incase someone who isn't tech savvy and new to Linux can install pi-ware easily.

Thank you :)

**Comment by gl91306** [comment]
> Also a suggestion in the readme on pi-ware include a way of installing python3, tk, ttkthemes and screeninfo
Incase someone who isn't tech savvy and new to Linux can install pi-ware easily.

Tk, ttkthemes and screeninfo are installed via the installscript on the repo, but I guess not everyone would have python installed, so ill keep that in mind

Thank you for the suggestion tho 👍
